version: '3.1'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
        - ./db_data:/var/lib/mysql
    restart: always
    environment:
        MYSQL_DATABASE: exampledb
        MYSQL_USER: exampleuser
        MYSQL_PASSWORD: examplepass
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
        - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
        - '9000:80'
    environment: 
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: examplepass
    networks: 
        - wpsite

  # Wordpress
  wordpress:
    depends_on: 
        - db
    image: wordpress:latest
    restart: always
    ports:
        - 9090:80
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: exampleuser
        WORDPRESS_DB_PASSWORD: examplepass
        WORDPRESS_DB_NAME: exampledb
    volumes:
        - ./wordpress:/var/www/html
    networks:
        - wpsite
    
networks:
    wpsite:
volumes:
    db_data: